### ISSUE TITLE
silk2pcm应来自于Skype的SILK Audio Codec

### ISSUE THREAD

**Issue by aflyhorse** [imfms/Tencent_SLK2WAV-Bat#2]
参见 https://web.archive.org/web/20130724103746/http://dev.skype.com/silk

**Comment by imfms** [comment]
看起来只有快照页面了，相关工具未能下载到验证，但看起来明显为此处出处，稍后会修改引用

**Comment by aflyhorse** [comment]
https://tools.ietf.org/html/draft-vos-silk-02#page-545
IETF的文档里有代码断章来着，silk2pcm应该是其中的Decoder

**Comment by imfms** [comment]
从帮助代码上对比了下，还真是，不太懂C，应该是找到的别人编译后的，这次是真长见识了，当初只是为了方便自己整理音频就去各种拆包找工具，工具找来后发现没有-version就懵逼了
